/* ============================================================== */
/* This file is automatically generated. Please do not modify it. */
/* ============================================================== */

using System;
using System.Runtime.InteropServices;

namespace Test
{
	public class Version
	{
		public const string Dll = "..\..\..\include\TestHeader";
	}
	
	public class UpdateArgs
	{
		public IntPtr ClassInstance;
		public void SetElapsedTime (IntPtr value)
		{
			Test_UpdateArgs_setElapsedTime(ClassInstance, value);
		}
		
		[DllImport(Version.Dll)]
		static extern private void Test_UpdateArgs_setElapsedTime (IntPtr classInstance, IntPtr value);
	}
	
	public class TestHeader
	{
		static public UpdateArgs CreateUpdateArgs ()
		{
			return new UpdateArgs{ ClassInstance = createUpdateArgs() };
		}
		
		[DllImport(Version.Dll)]
		static extern private IntPtr createUpdateArgs ();
	}
	
}

