/* ============================================================== */
/* This file is automatically generated. Please do not modify it. */
/* ============================================================== */

#include "..\..\..\include\TestHeader.h"

namespace Test
{
	extern "C" DLLEXPORT void API_CALL Test_UpdateArgs_setElapsedTime (IUpdateArgs * classInstance, void * value)
	{
		classInstance->setElapsedTime(value);
	}
	
}

