/* ============================================================== */
/* This file is automatically generated. Please do not modify it. */
/* ============================================================== */

#include <jni.h>
#include "TestHeader.h"

namespace Test
{
	extern "C" DLLEXPORT void API_CALL Test_IUpdateArgs_setElapsedTime (JNIEnv * env, jobject object, jlong classInstance, jlong shader, jlong value)
	{
		((IUpdateArgs *)classInstance)->setElapsedTime((Shaders)shader, (void *)value);
	}
	
	extern "C" DLLEXPORT jlong API_CALL Test_createUpdateArgs (JNIEnv * env, jobject object)
	{
		return (jlong)createUpdateArgs();
	}
	
}

